stages:
  data_preprocessing:
    cmd: python -m src.ML_pipelines.stage_01_data_preprocessing --config=params.yaml
    deps:
      - src\ML_pipelines\stage_01_data_preprocessing.py
    params:
      - data_source.data_source
      - preprocessed_data.preprocessed_data
    outs:
      - data\preprocessed\preprocessed.csv

  data_clustering:
    cmd: python -m src.ML_pipelines.stage_02_data_clustering --config=params.yaml
    deps:
      - src\ML_pipelines\stage_02_data_clustering.py
      - src\utils\common_utils.py
      - data\preprocessed\preprocessed.csv
    params:
      - elbow_method_parameters.init
      - elbow_method_parameters.title
      - elbow_method_parameters.xlabel
      - elbow_method_parameters.ylabel
      - elbow_method_parameters.figure_name
      - elbow_method_parameters.curve
      - elbow_method_parameters.direction
      - elbow_method_parameters.Cluster
      - elbow_method_parameters.clustered_dir
      - elbow_method_parameters.clustered_data
      - base.random_state
      - base.target_col
      - preprocessed_data.preprocessed_data
    outs:
      - data\clustered\clustered.csv