base:
  project: phishing_domain_detection_mlproject
  random_state: 42
  target_col: phishing
  test_size: 0.25
  sampling_strategy: minority

data_source:
  data_source: \data\processed\Input.csv

preprocessed_data:
  preprocessed_dir: \data\preprocessed
  train_data: \data\preprocessed\train.csv
  test_data: \data\preprocessed\test.csv

elbow_method_parameters:
  init: k-means++
  title: The Elbow Method
  xlabel: Number of clusters
  ylabel: WCSS
  figure_name_train: K-Means_Elbow_train.png
  figure_name_test: K-Means_Elbow_test.png
  curve: convex
  direction: decreasing
  Cluster: Cluster
  clustered_dir: \data\clustered
  clustered_train_data: \data\clustered\train_clustered.csv
  clustered_test_data: \data\clustered\test_clustered.csv